ci: add error suppression to argocd sync

diff --git a/.github/actions/argocd-sync-wait/action.yaml b/.github/actions/argocd-sync-wait/action.yaml
--- a/.github/actions/argocd-sync-wait/action.yaml
+++ b/.github/actions/argocd-sync-wait/action.yaml
@@ -61,18 +61,19 @@ runs:
         echo "🔄 Syncing app: $app"
 
         # Wait for any existing operation to complete before syncing
+        # https://github.com/argoproj/argo-cd/issues/4505#issuecomment-855980253
         argocd --auth-token "${{ inputs.ARGOCD_AUTH_TOKEN }}" \
                --server "${{ inputs.ARGOCD_SERVER_URL }}" \
                --grpc-web app wait \
                --timeout "${{ inputs.WAIT_TIMEOUT_SECONDS }}" \
                --operation \
-               --sync \
-               "$app" \
-        && \
-        argocd --auth-token "${{ inputs.ARGOCD_AUTH_TOKEN }}" \
-               --server "${{ inputs.ARGOCD_SERVER_URL }}" \
-               --grpc-web app sync \
-               --async "$app"
+               "$app"
+
+        # Using error suppression for "another operation is already in progress" errors
+        ( argocd --auth-token "${{ inputs.ARGOCD_AUTH_TOKEN }}" \
+                 --server "${{ inputs.ARGOCD_SERVER_URL }}" \
+                 --grpc-web app sync \
+                 --async "$app" || true )
       done
 
   - name: Run argocd wait
